#!/bin/sh

APP_ROOT={{ current_path }}
SHARED_PATH={{ shared_path }}
BUNDLE={{ bundle }}

cd $APP_ROOT || exit 1

#unset GIT_DIR
#NEWREF=$(cat /dev/stdin | cut -d ' ' -f 2) --uncomment this!

# Check out the new revision
#git reset --hard $NEWREF --uncomment this!

# Symlink shared files
rm -f $APP_ROOT/config/database.yml
ln -s $SHARED_PATH/config/database.yml $APP_ROOT/config/database.yml
#ln -s -f $SHARED_PATH/config/s3.yml $APP_ROOT/config/s3.yml
#ln -s -f $SHARED_PATH/config/newrelic.yml $APP_ROOT/config/newrelic.yml

# Install the required gems
# Note: the 'LANG=en_US.UTF-8' is a fix for jquery-rails 1.0.17...fails even though server has correct locale setting
LANG=en_US.UTF-8 $BUNDLE install --gemfile $APP_ROOT/Gemfile --path /home/ubuntu/.gem --deployment --without development test

# Update the DB schema
$BUNDLE exec rake RAILS_ENV=production db:migrate
$BUNDLE exec rake RAILS_ENV=production db:seed

# Note: Calling standard assets:precompile is overkill and chews up heaps of memory.
#       Hence do steps one-by-one
#echo Doing total bundle install thing
#$BUNDLE exec rake RAILS_ENV=production assets:precompile RAILS_GROUPS=assets
echo Doing asset:precompile:primary...
$BUNDLE exec rake RAILS_ENV=production assets:precompile:primary RAILS_GROUPS=assets
echo Doing asset:precompile:nondigest...
$BUNDLE exec rake RAILS_ENV=production assets:precompile:nondigest RAILS_GROUPS=assets

# Restart the unicorns
# We use stop/start instead of restart because the latter doesn't deal with Gemfile updates
service unicorn_{{ app }} stop 
sleep 5
service unicorn_{{ app }} start

# Tell bugsnag about the deploy, keeps the error history clean
$BUNDLE exec rake RAILS_ENV=production bugsnag:deploy TO=production
