
# from galaxy
- src: geerlingguy.security
  version: 1.5.0

- src: zzet.rbenv
  version: 3.0.0

- src: jdauphant.nginx
  version: v2.7.4

- src: geerlingguy.certbot
  version: 1.0.1

- src: conorsch.create-droplet
