---
# Make sure to insert secure passwords!!
db_password: lemonadespn
admin_password: Lemonadespnitt1

# Secret Token
# This is required to verify session. It must be at least 30 characters and
# random. This must be changed for a production server.
# Generate one with a bash command like: openssl rand -hex 128
secret_token: "54b2537c438181dcea220bdc76033903b5fbe582344c47d70be99f757bf48004166f415ae2c7a66ddec47c90644a22c8114fa405e5191568ed41f24219934ca27346acfec861dd1684c26b270d0f432edd01832b25bf31bb308f54e885467e77264bdd47aec42658b71b0446742268995eca0fdddb675202697e56e47d63cb85"

# Create a Google Maps API key and enable Javascript and Places libraries
google_maps_api_key: AIzaSyD4170BZE7opCx1KxHh0t9lRa_xCX_4TY0

# Mail settings
mail_host: smtp.transmail.com
mail_port: 587
smtp_username: emailapikey
smtp_password: vueCU2uLrZyA__323de7d46a608
# Optional mail settings
## Connection type 'TLS' means STARTTLS usually on port 587
## Connection type 'SSL' means SSL/TLS usually on port 465
 mail_secure_connection: 'TLS'
 mails_from: transmail@flaha.org
# mail_bcc: bcc_me@example.com

# Set these if using Amazon S3 for images or backups
#s3_access_key:
#s3_secret:
# Set this if using Amazon S3 for images:
#s3_images_bucket:
# Set this if using Amazon S3 for backups:
#s3_backups_bucket:
# Optional settings for Amazon S3 for images:
#s3_headers:
#s3_protocol:
# Optional settings for Amazon S3 for backups:
#s3_backups_region:

# Stripe Connect API keys, set these if you are using Stripe
# Find these under 'API keys' and 'Connect' in your Stripe account dashboard -> Account Settings
# Under 'Connect', the Redirect URI should be set to https://YOUR_SERVER_URL/stripe/callbacks (e.g. https://openfoodnetwork.org.uk/stripe/callbacks)
# Under 'Webhooks', you should set up a Connect endpoint pointing to https://YOUR_SERVER_URL/stripe/webhooks e.g. (https://openfoodnetwork.org.uk/stripe/webhooks)
# Different keys can be made for testing or live environments
#stripe_client_id: # ca_xxxx
#stripe_instance_secret_key: # sk_xxxx
#stripe_instance_publishable_key: # pk_xxxx
#stripe_endpoint_secret: # whsec_xxxx

# Skylight's API key. This enables performance instrumentation through Skylight. See https://github.com/openfoodfoundation/openfoodnetwork/pull/2070 for details.
#skylight_authentication: ""

# Datadog monitoring. See
# https://github.com/openfoodfoundation/ofn-install/issues/287 for details.
# Note we have a single OFN account where all servers send their metrics to.
#
# datadog_key: 'API_key_for_the_OFN_account'

# Bugsnag collects all errors and notifies you.
# https://github.com/openfoodfoundation/ofn-install/wiki/Issue-reporting
#
#bugsnag_key: ''

# Example settings for integrations like Zapier.
# ----------------------------------------------
# Generate a strong password with this command: `openssl rand -hex 128`.
#
# You can add one or multiple entries using the lists (with dashes), then run
# the `db_integrations.yml` playbook on the target server. Then, provision the
# server for the changes on the datadog agent to take place.
#
# To disable an integration, change the `state` key from `present` to: `absent`,
# remove the custom_* entries, then run the db_integrations.yml playbook again.

#db_integrations:
#  - { user: zapier, state: present, password: incredibly_strong_password_goes_here }

# For Datadog you will need the following:
#
#datadog_db_password: secure_password_goes_here
#
#db_integrations:
#  - { user: datadog, state: present, password: "{{ datadog_db_password }}" }
