- name: check service status
  service_facts:
  listen: reload unicorn configs

- name: reload unicorn configs
  service:
    name: unicorn_{{ app }}
    state: reloaded
  become: yes
  when: ansible_facts.services['unicorn_openfoodnetwork.service']['state'] == 'running'
