---
- name: deploy
  hosts: ofn_servers
  remote_user: "{{ user }}"
  sudo: yes
  sudo_user: "{{ unicorn_user }}"

  vars_files:
    - vars/default_vars.yml
    - host_vars/staging.vars.yml

  roles:
    - role: deploy
      notify:
        - restart unicorn

  handlers:
    - include: roles/webserver/handlers/main.yml
